BEGIN {
	RS = "\n:\n"
	FS = "\n"

	printf("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n") > outfile
	printf("<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n") >> outfile
	printf("<!-- Generated by cutter -->\n") >> outfile

	printf("<svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" width=\"%spx\" height=\"%spx\">\n", width, height) >> outfile
}

{
	file = $1
	transform = $2
	getline data < file
	close(file)
	gsub(/<\?xml[^>]*>/, "", data)
	gsub(/<![^>]*>/, "", data)
	gsub("<metadata.*</metadata>", "", data)
	gsub(/<svg[^>]*>/, "<g transform=\"" transform "\">", data)
	gsub(/<\/svg>/, "</g>", data)
	print data >> outfile
}

END {
	print "</svg>" >> outfile
}
